import { PIECE } from "../enums";

export const START_POSITIONS = [
  [
    PIECE.ROOK,
    PIECE.KNIGHT,
    PIECE.BISHOP,
    PIECE.QUEEN,
    PIECE.KING,
    PIECE.BISHOP,
    PIECE.KNIGHT,
    PIECE.ROOK,
  ],
  [
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
  ],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  [
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
    PIECE.PAWN,
  ],
  [
    PIECE.ROOK,
    PIECE.KNIGHT,
    PIECE.BISHOP,
    PIECE.QUEEN,
    PIECE.KING,
    PIECE.BISHOP,
    PIECE.KNIGHT,
    PIECE.ROOK,
  ],
];
