export enum ACTIONS {
  SET_POSSIBLE_MOVES = "SET_POSSIBLE_MOVES",
  CLEAR_POSSIBLE_MOVES = "CLEAR_POSSIBLE_MOVES",
  SET_TURN = "SET_TURN",
  GAME_OVER = "GAME_OVER",
  SET_PLAYER = "SET_PLAYER",
  SET_OPPONENT = "SET_OPPONENT",
  SET_PLAYER_COLOR = "SET_PLAYER_COLOR",
  SET_MESSAGE = "SET_MESSAGE",
  CLEAR_MESSAGE = "CLEAR_MESSAGE",
  SET_OPPONENT_MOVES = "SET_OPPONENT_MOVES",
  CLEAR_OPPONENT_MOVES = "CLEAR_OPPONENT_MOVES"
}
